site_name: Learn MKDocs
docs_dir: docs

plugins:
  - techdocs-core
  - search
  - git-authors
  # - glightbox:
  #     touchNavigation: false
  #     loop: false
  #     effect: zoom
  #     width: 100%
  #     height: auto
  #     zoomable: true
  #     draggable: true

theme: 
  name: material
  
nav:
  - Home: index.md
  - About: about.md
  - Show UML: show-uml.md